### ISSUE TITLE
Urcheon does not fail properly when the map compiler cannot be located.

### ISSUE THREAD

**Issue by Viech** [DaemonEngine/Urcheon#28]
When I run `urcheon build` I see the following lines in quick succession:
```
Building /home/eris/src/map-parpax_src.dpkdir/maps/parpax.map, stage: vis
Building /home/eris/src/map-parpax_src.dpkdir/maps/parpax.map, stage: nav
Building /home/eris/src/map-parpax_src.dpkdir/maps/parpax.map, stage: minimap
Creating MiniMap for: /home/eris/src/map-parpax_src.dpkdir/maps/parpax.map
Building /home/eris/src/map-parpax_src.dpkdir/maps/parpax.map, stage: light
```
This is immediately followed by `FileNotFoundError: [Errno 2] No such file or directory: '/home/eris/src/map-parpax_src.dpkdir/build/test/map-parpax_test.dpkdir/maps/parpax.bsp'`.

All is fine when I make `q3map2` available by running `PATH="$PATH:/opt/netradiant" urcheon build` instead. Urcheon should give a proper error message and terminate immediately when the map compiler cannot be found.

**Comment by illwieckz** [comment]
Thanks for noticing this, I forgot to raise the exceptions to the parent process. :wink:
