### ISSUE TITLE
Mistake in q3legacybrush_plane_pattern pattern?

### ISSUE THREAD

**Issue by martin-t** [DaemonEngine/Urcheon#32]
According to all docs I've read (including the comment here) rotation is before scale but the pattern puts rotation [after](https://github.com/DaemonEngine/Urcheon/blob/master/Urcheon/Map.py#L101) scale. I haven't yet used the parsed data so can't confirm, just don't want this to be forgotten.

**Comment by illwieckz** [comment]
it's a mistake, you're right
